import Head from "next/head";
import Link from "next/link";

export default function PageTwo() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Page: Two</h2>
        <Link href="/">Take me back to page one</Link>
      </main>
    </>
  );
}
